version: "3"
services:
  nginx:
    container_name: sample-nginx
    image: nginx
    ports:
      - "80:80"
      - "444:443"
    volumes:
      - ./src/:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./nginx/crt:/etc/nginx/ssl_key
    networks:
      - sample-network
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: sample-php
    volumes:
      - ./src:/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - sample-network
  mysql:
    image: mysql:5.7
    container_name: sample-mysql
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - sample-network
  redis:
    image: redis
    container_name: sample-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - sample-network
    volumes:
      - ./redis/config:/docker/config
      - ./redis/data:/data
    command: redis-server /docker/config/redis.conf
networks:
  sample-network:
